[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线版

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持


ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]低级节点自动`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.gstatic.com/generate_204`900,5,100
custom_proxy_group=低级节点自动`url-test`(^(?!.*(高级)).*)`https://www.gstatic.com/generate_204`900,5,100
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`[]低级节点自动
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`[]低级节点自动`.*

enable_rule_generator=true
overwrite_original_rules=true

